// Offline shell. Generated by tools/make-sw.py (optional: the worker is network-first, so uploaded code is picked up without regenerating it).
// Online, every request revalidates against the server and refreshes the cache; the cache is only the offline fallback.
const VERSION = 'pixoto-cameraraw1';
const FILES = [
 "./",
 "app.js",
 "assets/apple-touch-icon.png",
 "assets/favicon-32.png",
 "assets/icon-192.png",
 "assets/icon-512.png",
 "assets/icon-maskable-512.png",
 "assets/icon.svg",
 "assets/icons.svg",
 "core/blend.js",
 "core/commands.js",
 "core/compute.js",
 "core/effects.js",
 "core/filters/adjust.js",
 "core/filters/blur.js",
 "core/filters/cameraraw.js",
 "core/filters/filters.js",
 "core/filters/lut.js",
 "core/filters/painterly.js",
 "core/geom.js",
 "core/history.js",
 "core/limits.js",
 "core/live.js",
 "core/mask.js",
 "core/model.js",
 "core/ops/canvas.js",
 "core/ops/clipboard.js",
 "core/ops/gradient.js",
 "core/ops/guides.js",
 "core/ops/layers.js",
 "core/ops/live.js",
 "core/ops/paint.js",
 "core/ops/pixels.js",
 "core/ops/preview.js",
 "core/ops/selection.js",
 "core/ops/transform.js",
 "core/paint/inpaint.js",
 "core/paint/stroke.js",
 "core/pixels.js",
 "core/render.js",
 "core/select/wand.js",
 "core/sepblend.js",
 "core/shape.js",
 "core/state.js",
 "core/text/editor.js",
 "core/text/layout.js",
 "core/text/style.js",
 "core/tools.js",
 "css/app.css",
 "index.html",
 "io/files.js",
 "io/project.js",
 "io/psd.js",
 "io/store.js",
 "io/zip.js",
 "manifest.webmanifest",
 "ui/adjust-dialogs.js",
 "ui/camera-raw-dialog.js",
 "ui/canvas-view.js",
 "ui/color-picker.js",
 "ui/dialogs.js",
 "ui/dom.js",
 "ui/fonts.js",
 "ui/guides-ui.js",
 "ui/help.js",
 "ui/last-filter.js",
 "ui/layers-panel.js",
 "ui/live-dialog.js",
 "ui/menu.js",
 "ui/options-bar.js",
 "ui/popup.js",
 "ui/shortcuts-dialog.js",
 "ui/tabs.js",
 "ui/tool-dialogs.js",
 "ui/toolbar.js",
 "ui/tools/brush.js",
 "ui/tools/common.js",
 "ui/tools/crop.js",
 "ui/tools/gradient.js",
 "ui/tools/move.js",
 "ui/tools/selection.js",
 "ui/tools/shape.js",
 "ui/tools/text.js",
 "ui/tools/view-tools.js",
 "workers/compute.worker.js"
];
self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(VERSION).then((c) => Promise.all(FILES.map((f) => c.add(new Request(f, { cache: 'reload' })).catch(() => {})))).then(() => self.skipWaiting()));
});
self.addEventListener('activate', (e) => {
  e.waitUntil((async () => {
    for (const k of await caches.keys()) if (k !== VERSION) await caches.delete(k);
    await self.clients.claim();
    // Pages still running code from the previous worker reload once onto the new code.
    for (const c of await self.clients.matchAll({ type: 'window' })) c.navigate(c.url).catch(() => {});
  })());
});
self.addEventListener('fetch', (e) => {
  const req = e.request, url = new URL(req.url);
  if (req.method !== 'GET' || url.origin !== location.origin) return;
  e.respondWith((async () => {
    const cache = await caches.open(VERSION);
    try {
      const res = await fetch(req, { cache: 'no-cache' });
      if (res.ok) cache.put(req, res.clone());
      return res;
    } catch (err) {
      const hit = await cache.match(req, { ignoreSearch: true });
      if (hit) return hit;
      throw err;
    }
  })());
});
