// Offline shell. Generated by tools/make-sw.py: precaches every file so the editor works offline after the first visit.
const VERSION = 'pixoto-da8d37a298';
const FILES = [
 "./",
 "app.js",
 "assets/apple-touch-icon.png",
 "assets/favicon-32.png",
 "assets/icon-192.png",
 "assets/icon-512.png",
 "assets/icon-maskable-512.png",
 "assets/icon.svg",
 "assets/icons.svg",
 "core/blend.js",
 "core/commands.js",
 "core/compute.js",
 "core/effects.js",
 "core/filters/adjust.js",
 "core/filters/blur.js",
 "core/filters/filters.js",
 "core/filters/painterly.js",
 "core/geom.js",
 "core/history.js",
 "core/limits.js",
 "core/live.js",
 "core/mask.js",
 "core/model.js",
 "core/ops/canvas.js",
 "core/ops/clipboard.js",
 "core/ops/gradient.js",
 "core/ops/guides.js",
 "core/ops/layers.js",
 "core/ops/live.js",
 "core/ops/paint.js",
 "core/ops/pixels.js",
 "core/ops/preview.js",
 "core/ops/selection.js",
 "core/ops/transform.js",
 "core/paint/inpaint.js",
 "core/paint/stroke.js",
 "core/pixels.js",
 "core/render.js",
 "core/select/wand.js",
 "core/sepblend.js",
 "core/shape.js",
 "core/state.js",
 "core/text/editor.js",
 "core/text/layout.js",
 "core/text/style.js",
 "core/tools.js",
 "css/app.css",
 "index.html",
 "io/files.js",
 "io/project.js",
 "io/psd.js",
 "io/store.js",
 "io/zip.js",
 "manifest.webmanifest",
 "ui/adjust-dialogs.js",
 "ui/canvas-view.js",
 "ui/color-picker.js",
 "ui/dialogs.js",
 "ui/dom.js",
 "ui/fonts.js",
 "ui/guides-ui.js",
 "ui/last-filter.js",
 "ui/layers-panel.js",
 "ui/live-dialog.js",
 "ui/menu.js",
 "ui/options-bar.js",
 "ui/popup.js",
 "ui/shortcuts-dialog.js",
 "ui/tabs.js",
 "ui/tool-dialogs.js",
 "ui/toolbar.js",
 "ui/tools/brush.js",
 "ui/tools/common.js",
 "ui/tools/crop.js",
 "ui/tools/gradient.js",
 "ui/tools/move.js",
 "ui/tools/selection.js",
 "ui/tools/shape.js",
 "ui/tools/text.js",
 "ui/tools/view-tools.js",
 "workers/compute.worker.js"
];
self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(VERSION).then((c) => Promise.all(FILES.map((f) => c.add(f).catch(() => {})))).then(() => self.skipWaiting()));
});
self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys().then((keys) => Promise.all(keys.filter((k) => k !== VERSION).map((k) => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', (e) => {
  const req = e.request, url = new URL(req.url);
  if (req.method !== 'GET' || url.origin !== location.origin) return;
  // Cache first (everything is precached); the network fills in anything new and refreshes the cache.
  e.respondWith(caches.open(VERSION).then(async (cache) => {
    const hit = await cache.match(req, { ignoreSearch: true });
    const net = fetch(req).then((res) => { if (res.ok) cache.put(req, res.clone()); return res; }).catch(() => hit);
    return hit || net;
  }));
});
