#!/usr/bin/env python3
"""Writes app/sw.js: the offline service worker with a precache list of every file in app/ (run after adding or removing files)."""
import os, hashlib, json
ROOT = os.path.join(os.path.dirname(__file__), '..', 'app')
files = []
for d, _, fs in os.walk(ROOT):
    for f in sorted(fs):
        p = os.path.relpath(os.path.join(d, f), ROOT)
        if p in ('sw.js',) or f.startswith('.'): continue
        files.append(p.replace(os.sep, '/'))
files.sort()
h = hashlib.sha1()
for f in files: h.update(f.encode()); h.update(open(os.path.join(ROOT, f), 'rb').read())
version = 'pixoto-' + h.hexdigest()[:10]
src = f"""// Offline shell. Generated by tools/make-sw.py (optional: the worker is network-first, so uploaded code is picked up without regenerating it).
// Online, every request revalidates against the server and refreshes the cache; the cache is only the offline fallback.
const VERSION = '{version}';
const FILES = {json.dumps(['./'] + files, indent=1)};
self.addEventListener('install', (e) => {{
  e.waitUntil(caches.open(VERSION).then((c) => Promise.all(FILES.map((f) => c.add(new Request(f, {{ cache: 'reload' }})).catch(() => {{}})))).then(() => self.skipWaiting()));
}});
self.addEventListener('activate', (e) => {{
  e.waitUntil((async () => {{
    for (const k of await caches.keys()) if (k !== VERSION) await caches.delete(k);
    await self.clients.claim();
    // Pages still running code from the previous worker reload once onto the new code.
    for (const c of await self.clients.matchAll({{ type: 'window' }})) c.navigate(c.url).catch(() => {{}});
  }})());
}});
self.addEventListener('fetch', (e) => {{
  const req = e.request, url = new URL(req.url);
  if (req.method !== 'GET' || url.origin !== location.origin) return;
  e.respondWith((async () => {{
    const cache = await caches.open(VERSION);
    try {{
      const res = await fetch(req, {{ cache: 'no-cache' }});
      if (res.ok) cache.put(req, res.clone());
      return res;
    }} catch (err) {{
      const hit = await cache.match(req, {{ ignoreSearch: true }});
      if (hit) return hit;
      throw err;
    }}
  }})());
}});
"""
open(os.path.join(ROOT, 'sw.js'), 'w').write(src)
print('wrote sw.js with', len(files), 'files,', version)
