#!/usr/bin/env python3
"""Writes app/sw.js: the offline service worker with a precache list of every file in app/ (run after adding or removing files)."""
import os, hashlib, json
ROOT = os.path.join(os.path.dirname(__file__), '..', 'app')
files = []
for d, _, fs in os.walk(ROOT):
    for f in sorted(fs):
        p = os.path.relpath(os.path.join(d, f), ROOT)
        if p in ('sw.js',) or f.startswith('.'): continue
        files.append(p.replace(os.sep, '/'))
files.sort()
h = hashlib.sha1()
for f in files: h.update(f.encode()); h.update(open(os.path.join(ROOT, f), 'rb').read())
version = 'pixoto-' + h.hexdigest()[:10]
src = f"""// Offline shell. Generated by tools/make-sw.py: precaches every file so the editor works offline after the first visit.
const VERSION = '{version}';
const FILES = {json.dumps(['./'] + files, indent=1)};
self.addEventListener('install', (e) => {{
  e.waitUntil(caches.open(VERSION).then((c) => Promise.all(FILES.map((f) => c.add(f).catch(() => {{}})))).then(() => self.skipWaiting()));
}});
self.addEventListener('activate', (e) => {{
  e.waitUntil(caches.keys().then((keys) => Promise.all(keys.filter((k) => k !== VERSION).map((k) => caches.delete(k)))).then(() => self.clients.claim()));
}});
self.addEventListener('fetch', (e) => {{
  const req = e.request, url = new URL(req.url);
  if (req.method !== 'GET' || url.origin !== location.origin) return;
  // Cache first (everything is precached); the network fills in anything new and refreshes the cache.
  e.respondWith(caches.open(VERSION).then(async (cache) => {{
    const hit = await cache.match(req, {{ ignoreSearch: true }});
    const net = fetch(req).then((res) => {{ if (res.ok) cache.put(req, res.clone()); return res; }}).catch(() => hit);
    return hit || net;
  }}));
}});
"""
open(os.path.join(ROOT, 'sw.js'), 'w').write(src)
print('wrote sw.js with', len(files), 'files,', version)
